vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/coordinateimages
            upload_destination: '%kernel.project_dir%/public/images/coordinateimages'
