vich_uploader:
    db_driver: orm

    mappings:
        coordinate:
            uri_prefix: /images/uploads/coordinateimages
            upload_destination: '%kernel.project_dir%/public/images/uploads/coordinateimages'
