version: "2"

services:
  nginx.symfony:
    container_name: nginx.symfony
    image: nginx:1.13.10
    volumes:
      - ../:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:8443:443

  php.symfony:
    container_name: php.symfony
    image: php.symfony
    environment:
      - APP_ENV=dev
      - APP_SECRET=31ab70e5aea4699ba61deddc8438d2f1
      - DATABASE_URL=mysql://root:p9iijKcfgENjBWDYgSH7@mysql.symfony:3306/symfony
    volumes:
      - ../:/code

  mysql.symfony:
    container_name: mysql.symfony
    image: mysql:5.7.21
    environment:
      - MYSQL_ROOT_PASSWORD=p9iijKcfgENjBWDYgSH7
    volumes:
      - ./mysql-data/:/var/lib/mysql
    ports:
      - 127.0.0.1:13306:3306

  frontend.symfony:
    container_name: frontend.symfony
    image: frontend.symfony
    volumes:
      - ../:/code

  selenium.symfony:
      container_name: selenium.symfony
      image: selenium/standalone-chrome-debug
      ports:
      - 127.0.0.1:4444:4444 # To debug selenium API
      - 127.0.0.1:5900:5900 # To connect via VNC
